[package]
name = "go_version_manager"
version = "0.7.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"
description = "A small program to download chosen golang version"
readme = "README.md"
homepage = "https://github.com/x0f5c3/go_version_manager"
repository = "https://github.com/x0f5c3/go_version_manager"
license-file = "LICENSE"
keywords = ["golang","packages","download"]
categories = ["command-line-utilities","development-tools"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "0.5.1"
pretty_env_logger = "0.4.0"
tokio = { version = "^1", features = ["macros"]}
versions = { version = "3.0.3", features = ["serde"] }
indicatif = { version = "0.16.0", features = ["rayon", "improved_unicode"] }
human-panic = "1.0.3"
structopt = "0.3.21"
console = "0.14.0"
reqwest = { version = "0.11.3", features = ["rustls"] }
manic = { version = "0.7.0", features = ["progress", "json"] }
thiserror = "1.0.22"
dialoguer = "0.8.0"
quit = "1.1.2"
duct = "0.13.5"
leg = "1.0.0"
rayon = "1.5.1"
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = ["derive"] }
colored = "^2.0.0"

[target.'cfg(windows)'.dependencies]
zip = "0.5.13"
zip-extensions = "0.6.1"

[target.'cfg(not(windows))'.dependencies]
async-compression = { version = "0.3.8", features = ["all"] }
tar = "0.4.37"

[badges]
github = { repository = "x0f5c3/go_version_manager" }
