[package]
name = "go_version_manager"
version = "0.7.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"
description = "A small program to download chosen golang version"
readme = "README.md"
homepage = "https://github.com/x0f5c3/go_version_manager"
repository = "https://github.com/x0f5c3/go_version_manager"
license-file = "LICENSE"
keywords = ["golang","packages","download"]
categories = ["command-line-utilities","development-tools"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "0.5.0"
tokio = { version = "^1", features = ["macros"]}
versions = "2.0.1"
indicatif = "0.15.0"
human-panic = "1.0.3"
structopt = "0.3.21"
console = "0.14.0"
manic = { git = "https://github.com/x0f5c3/manic", branch = "hyper", features = ["progress", "json", "compress"] }
thiserror = "1.0.22"
hyper = { version = "0.14.2", features = ["client", "http1", "http2", "runtime"] }
dialoguer = "0.7.1"
quit = "1.1.2"
duct = "*"
leg = "1.0.0"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
colored = "^1.8.0"


[badges]
github = { repository = "x0f5c3/go_version_manager" }
