[package]
name = "golang_downloader"
version = "0.1.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "*"
reqwest = { version = "*", features = ["json", "blocking"]}
tokio = { version = "*", features = ["full"]}
sha2 = "*"
duct = "*"
versions = "*"
indicatif = "*"
human-panic = "*"
structopt = "*"
openssl = { version = "*", features = ["vendored"] }
