[package]
name = "go_version_manager"
version = "0.7.0"
authors = ["x0f5c3 <x0f5c3@tutanota.com>"]
edition = "2018"
description = "A small program to download chosen golang version"
readme = "README.md"
homepage = "https://github.com/x0f5c3/go_version_manager"
repository = "https://github.com/x0f5c3/go_version_manager"
license-file = "LICENSE"
keywords = ["golang","packages","download"]
categories = ["command-line-utilities","development-tools"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soup = "0.5.1"
pretty_env_logger = "0.4.0"
versions = { version = "3.0.3", features = ["serde"] }
indicatif = { version = "0.16.0", features = ["rayon", "improved_unicode"] }
human-panic = "1.0.3"
structopt = { version = "0.3.21", features = ["paw"] }
directories = "4.0.1"
paw = "*"
console = "0.14.0"
git2 = { version = "*", features = ["vendored-libgit2"] }
reqwest = { version = "0.11.3", features = ["rustls", "blocking"] }
thiserror = "1.0.22"
dialoguer = "0.8.0"
quit = "1.1.2"
duct = "*"
serde_json = "1.0.69"
paris = { version = "*", features = ["macros"] }
rayon = "*"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
flate2 = "1.0.22"
toml_edit = { version = "*", features = ["easy"] }
tar = "*"

[dependencies.manic]
version = "*"
default-features = false
features = ["progress", "json", "threaded"]

[target.'cfg(windows)'.dependencies]
zip = "*"
zip-extensions = "*"

[target.'cfg(not(windows))'.dependencies]

[badges]
github = { repository = "x0f5c3/go_version_manager" }
