#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
pub const FILE_EXT: &str = "linux-amd64.tar.gz";
#[cfg(all(target_os = "linux", target_arch = "x86"))]
pub const FILE_EXT: &str = "linux-386.tar.gz";
#[cfg(all(target_os = "linux", target_arch = "aarch64"))]
pub const FILE_EXT: &str = "linux-arm64.tar.gz";
#[cfg(all(target_os = "linux", target_arch = "arm"))]
pub const FILE_EXT: &str = "linux-armv6l.tar.gz";
#[cfg(all(target_os = "linux", target_arch = "powerpc64"))]
pub const FILE_EXT: &str = "linux-ppc64le.tar.gz";
#[cfg(all(target_os = "linux", target_arch = "s390x"))]
pub const FILE_EXT: &str = "linux-s390x.tar.gz";
#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
pub const FILE_EXT: &str = "windows-amd64.msi";
#[cfg(all(target_os = "windows", target_arch = "x86"))]
pub const FILE_EXT: &str = "windows-386.msi";
#[cfg(all(target_os = "macos", target_arch = "x86_64"))]
pub const FILE_EXT: &str = "darwin-amd64.pkg";
#[cfg(all(target_os = "freebsd", target_arch = "x86_64"))]
pub const FILE_EXT: &str = "freebsd-amd64.tar.gz";
#[cfg(all(target_os = "freebsd", target_arch = "x86"))]
pub const FILE_EXT: &str = "freebsd-386.tar.gz";

pub const DL_URL: &str = "https://golang.org/dl";
