name: Publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/golang_downloader
        asset_name: golang_downloader-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
