name: Publish-on-tag

on:
  push:
    tags:
      - '*'

jobs:
  build_x64:
    name: Publish binaries x64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/golang_downloader
        asset_name: golang_downloader-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
  build_arm64:
    name: Publish binaries arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
         use-cross: true
         command: build
         args: --release --target aarch64-unknown-linux-gnu
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/aarch64-unknown-linux-gnu/release/golang_downloader
          asset_name: golang_downloader-linux-arm64
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
