name: Fmt and Clippy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run fmt
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings
